# Generated by Django 2.1.4 on 2019-01-18 06:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aws',
            fields=[
                ('name', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('amount', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='amount')),
                ('price', models.IntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='price')),
                ('sales', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='sales')),
            ],
        ),
    ]
