# Generated by Django 2.1.4 on 2019-01-21 06:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aws',
            fields=[
                ('name', models.CharField(blank=True, default='', help_text='リクエストパラメータのnameを格納', max_length=8, primary_key=True, serialize=False, unique=True, verbose_name='商品名')),
                ('amount', models.IntegerField(blank=True, default=0, help_text='リクエストパラメータのamountを格納', validators=[django.core.validators.RegexValidator(code='Disallowed Tags', flags=None, inverse_match=None, message='正の整数を格納してください', regex='^[1-9][0-9]*$')], verbose_name='在庫数')),
                ('price', models.IntegerField(blank=True, default=1, help_text='リクエストパラメータのpriceを格納', validators=[django.core.validators.RegexValidator(code='Disallowed Tags', flags=None, inverse_match=None, message='正の整数を格納してください', regex='^[1-9][0-9]*$')], verbose_name='商品価格')),
                ('sales', models.IntegerField(blank=True, default=0, help_text='リクエストパラメータpriceが設定されたら，price x amountを格納', validators=[django.core.validators.RegexValidator(code='Disallowed Tags', flags=None, inverse_match=None, message='0以上の整数を格納してください', regex='^[0-9]*$')], verbose_name='売り上げ')),
            ],
        ),
    ]
