# Generated by Django 2.1.4 on 2019-01-20 07:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aws', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aws',
            name='amount',
            field=models.IntegerField(blank=True, default=0, help_text='リクエストパラメータのamountを格納', validators=[django.core.validators.MinValueValidator(0)], verbose_name='在庫数'),
        ),
        migrations.AlterField(
            model_name='aws',
            name='name',
            field=models.CharField(blank=True, default='', help_text='リクエストパラメータのnameを格納', max_length=8, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(8)], verbose_name='商品名'),
        ),
        migrations.AlterField(
            model_name='aws',
            name='price',
            field=models.IntegerField(blank=True, default=1, help_text='リクエストパラメータのpriceを格納', validators=[django.core.validators.MinValueValidator(1)], verbose_name='商品価格'),
        ),
        migrations.AlterField(
            model_name='aws',
            name='sales',
            field=models.IntegerField(blank=True, default=0, help_text='リクエストパラメータのsalesを格納', validators=[django.core.validators.MinValueValidator(0)], verbose_name='売り上げ'),
        ),
    ]
