# Generated by Django 2.1.4 on 2019-01-20 08:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aws', '0007_auto_20190120_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aws',
            name='amount',
            field=models.FloatField(blank=True, default=0, help_text='リクエストパラメータのamountを格納', validators=[django.core.validators.RegexValidator(message='正の整数を格納してください', regex='^[1-9][0-9]*')], verbose_name='在庫数'),
        ),
    ]
